### ISSUE TITLE
Some Feature Request Ideas

### ISSUE THREAD

**Issue by UltimaScripts** [bittiez/TazUO#123]
### Colored Tooltip Text For Item Properties
An enhancement to the already included property highlight feature. But can be seperate aswell.
Allow players to apply hues to specific properties or text in the tooltip.

here is an example of how servuo changes font color.
`string msg = String.Format ( "<basefont color='ff0000'>example text.</basefont>");`

### Music Selection/Custom Music Playlist or Override
allow the player to select specific music to play.
Use of a new specific directory to play custom music located within it.
Override default music with custom music, for example changing the combat music to something else.

### Skill Progress Bar
Mostly a visual thing, just a progress bar to visualize the players current skill vs max skill

### Custom Fonts
Ability to use fonts other than those provided in the fonts.mul
There are various places fonts are used in CUO, This idea is mostly specific to Tooltips.
So the user can use a custom font that is easier on their eyes or displays more clearly.

### Tile Markers
Add a hued square to an x y z map location

### Radius/Distance Markers
A visual square around the player at a set distance

### Transparent Player without Hiding/Invis Active
Just like how it applies a hue and transparency to the PC, just always on or toggle-able.

**Comment by bittiez** [comment]
Decent ideas, don't have time to reply to each one right now but feel free to join our Discord for community discussion on ideas like this 👍  I like most of these ideas though (Fonts are already a work in progress)

**Comment by bittiez** [comment]
These have all been implemented as of the next release, thank you for the suggestions.
