### ISSUE TITLE
ModernOptionGump unicode support

### ISSUE THREAD

**Issue by fanfanya123** [bittiez/TazUO#207]
I try to translate the option gump into unicode string, but it doesn't show correctly in the game, all changed lable/menu display as blank, it  seems the ModenrOptionGump.cs file doesn't support unicode string display. 
![Untitled](https://github.com/bittiez/TazUO/assets/73729943/f6f97187-9cac-4765-b645-563e7f8963ae)

**Comment by bittiez** [comment]
Make sure your ttf font file actually has those characters

**Comment by fanfanya123** [comment]
ttf font is in the Fonts folder, it works OK, because other unicode display work correctly, such as system chat....

**Comment by bittiez** [comment]
Where did you change the text at? Can you show your changes?

**Comment by bittiez** [comment]
Ah I see, the options menu uses the embedded font, you can change that to a
string with your font name in your fonts folder like "roboto"

**Comment by bittiez** [comment]
There is a small crowd of foreign players using TUO, maybe I will try to put in an easier translation system

**Comment by fanfanya123** [comment]
There is also another buttons need unicode support in this file, such as below:

_mainContent.AddToLeft(b = CategoryButton("常规", (int)PAGE.General, mainContent.LeftWidth));_
....
content.AddToRight(new CheckboxWithLabel("高亮指示鼠标选择物品", isChecked: profile.HighlightGameObjects, valueChanged: (b) => { profile.HighlightGameObjects = b; }), true, page);

are they also because of the embedded font ?

**Comment by bittiez** [comment]
Yes, you can use a replace tool, replace this:
`TrueTypeLoader.EMBEDDED_FONT`
with your font
`"Some font name"`

In the entire file

In the next update I will try to make this easier

**Comment by bittiez** [comment]
https://github.com/bittiez/TazUO/commit/2f4f6b929c3345add44b242b69739f62ee3e82ad

If you want to wait I will try to get this update done in a few days, then there will be a language.json file you can more easily edit and hopefully share your translation that I can put on the repo for others to use 👍

**Comment by bittiez** [comment]
Let me know if your issue was solved for the font missing unicode chars

**Comment by fanfanya123** [comment]
It doesn't work.
I tested it in below step:
1)translate the language.json, as below picture.then save the file.
![1](https://github.com/bittiez/TazUO/assets/73729943/28efee0a-096c-48dd-9dd6-d48741b99c51)
2)I run the classicuo.exe, then the language.json file was updated automaticly, as below picture:
![2](https://github.com/bittiez/TazUO/assets/73729943/d53c1e53-139b-4aad-b1bd-563a94a0eade)
3)In game, the menue doen't show correctly. as below picture:
![3](https://github.com/bittiez/TazUO/assets/73729943/deff09b3-3ce5-4bac-9bb9-c9b9206c76bb)

**Comment by bittiez** [comment]
Hmm. What language is that? By default this menu is using Roboto-Regular, and looking on google's font database I don't see Chinese/Japanese/Korean which forgive me if I'm wrong but I think that may be one of those three.

You can either edit [this line](https://github.com/bittiez/TazUO/blob/main/src/ClassicUO.Client/Game/UI/Gumps/ModernOptionsGump.cs#L6262C41-L6262C55) with your font 
*or* download a font that supports that language and rename it `Roboto-Regular.ttf` and put it in your Fonts folder

**Comment by fanfanya123** [comment]
Ok, it's sovled finally by below steps:
1)Transfer the language.json file into unicode format.
2)Make sure the Roboto-Regular.ttf file is in the Fonts folder.

Many thanks for you ! @bittiez

**Comment by bittiez** [comment]
Excellent, glad it's solved!
