### ISSUE TITLE
Disabling update check? 

### ISSUE THREAD

**Issue by ilovebittiez** [bittiez/TazUO#213]
Is there a way to disable the update check?  i get red messages in game telling me to update, i wish there was an option to disable those checks, sometimes i dont feel like updating. Thanks for this amazin client!

**Comment by bittiez** [comment]
You can add `-skipupdatecheck` as an arg when launching TUO

`./ClassicUO.exe -skipupdatecheck`

The launcher sends this automatically if you decide to use that instead
